name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: "Target platform (e.g., linux/amd64, linux/arm64/v8)"
        required: false
        default: "linux/amd64"
      tag:
        description: "Tag for the Docker image"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform ${{ inputs.platform }} \
            --build-arg PLATFORM=${{ inputs.platform }} \
            --tag ghcr.io/${{ github.repository_owner }}/unmonitorr:${{ inputs.tag }} \
            --output=type=image,push=true \
            --provenance=false \
            .
